CREATE DATABASE Connect_Plus

GO
USE Connect_Plus

CREATE TABLE TipoContato (
    IdTipoContato UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
    Titulo VARCHAR(100) NOT NULL
);
SELECT * FROM TipoContato
GO

CREATE TABLE Contato (
    IdContato UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())), 
    Nome VARCHAR(150) NOT NULL,
    FormaContato VARCHAR(150) NOT NULL,
    CaminhoImagem VARCHAR(255),
    
    IdTipoContato UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoContato(IdTipoContato)
);
SELECT * FROM Contato
GO


